### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [astrolabe-expeditions/SensOcean#1]
In the file "SensOcean/SensOcean-ESP32/SensOcean-ESP32.ino" the `Wire.requestFrom()` is followed by a `Wire.endTransmission()`.
That `Wire.endTransmission()` is at the moment at line 215 and may be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).
Can you tell what the origin of this bug is ? I see a lot lately.

**Comment by anthoninlize** [comment]
Hey, thank you for your feedback on this, and sorry for this late reply.
Actually this piece of code came originally from the sample code provided by the sensor manufacturer, on their website. 
See the sample code at https://www.atlas-scientific.com/product_pages/kits/ec_k1_0_kit.html

But we'll remove this line and follow your advice, thanks.

**Comment by Koepel** [comment]
AtlasScientific responded very fast, they are working on it right now.
